/** Theme tokens taken verbatim from the Stitch design of the admin dashboard. */
module.exports = {
  content: ["../app/static/index.html", "../app/static/js/**/*.js"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b1c5ff",
        "surface-tint": "#345baf",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "tertiary-container": "#004c32",
        "on-surface-variant": "#434652",
        outline: "#747783",
        "on-secondary-container": "#fefbff",
        "surface-bright": "#f9f9ff",
        "surface-dim": "#cfdaf2",
        "on-error-container": "#93000a",
        "surface-variant": "#d8e3fb",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-surface": "#111c2d",
        "secondary-container": "#2b69fd",
        "on-tertiary-container": "#2bc58c",
        "on-primary-fixed": "#001947",
        "on-secondary-fixed-variant": "#003cac",
        "surface-container-high": "#dee8ff",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-container": "#8dadff",
        "secondary-fixed": "#dbe1ff",
        primary: "#002869",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#00174d",
        "surface-container": "#e7eeff",
        "on-primary": "#ffffff",
        "primary-fixed": "#dae2ff",
        "on-tertiary-fixed-variant": "#005236",
        surface: "#f9f9ff",
        "primary-fixed-dim": "#b1c5ff",
        "secondary-fixed-dim": "#b5c4ff",
        "inverse-on-surface": "#ecf1ff",
        secondary: "#004fda",
        "surface-container-low": "#f0f3ff",
        "on-tertiary-fixed": "#002113",
        "primary-container": "#0b3d91",
        background: "#f9f9ff",
        "inverse-surface": "#263143",
        "surface-container-highest": "#d8e3fb",
        "on-background": "#111c2d",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#144296",
        "outline-variant": "#c4c6d3",
        tertiary: "#003321",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        margin: "1rem",
        gutter: "1.25rem",
        "space-xs": "0.25rem",
        "space-xl": "2rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "gutter-desktop": "1.5rem",
      },
      fontFamily: {
        "label-sm": ["Inter", "system-ui", "sans-serif"],
        "code-sm": ["JetBrains Mono", "ui-monospace", "monospace"],
        "label-md": ["Inter", "system-ui", "sans-serif"],
        "code-md": ["JetBrains Mono", "ui-monospace", "monospace"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "system-ui", "sans-serif"],
        "headline-xl": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "code-sm": ["11px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "code-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
